<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-02-17T05:46:51+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Scoop Therapy',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1455684411,
    ),
);
