<footer id="footer-wrapper" class="fixed-footer"><!-- container-fluid -->
	<div class="v-align-table">
		<div class="v-align-table-cell">
			<div class="copyright">
				<p>© 2015 Scoop Therapy. All Rights Reserved.</p>
				<p>No part of this website, designs, layouts or any of its contents may be reproduced, copied, modified or adapted, without the prior written consent of Scoop Therapy. </p>
			</div>
			<ul>
				<li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
				<li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
				<li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
				<li><a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a></li>
			</ul>
		</div>
	</div>							
</footer>