<div id="menu-logo-wrapper" class="animated slideInDown hidden-xs hidden-sm">
	
	<div class="main-menu">		
		<div class="pull-left">
			<div class="toggle-menu-container">					
				<div class="toggle-menu">
					<a href="javascript:void(0)"> 
						<span class="nav-bar"></span> 
						<span class="nav-bar"></span> 
						<span class="nav-bar"></span> 
					</a> 
				</div>
			</div>
			<div class="main-nav-wrapper">
				<ul class="main-nav">
					<li><a href="about.html">About</a></li>
					<li><a href="flavours.html">Flavours</a></li>
					<li><a href="news.html">News</a></li>
					<li><a href="locate.html">Locate</a></li>
					<li><a href="contact.html">Contact</a></li>						
					<li><a href="join-us.html">Join Us</a></li>				
				</ul>				
			</div>
		</div>
		<a href="index.html" class="logo pull-right"><img src="images/logos/main-logo.png" alt=""></a>				
	</div>	

</div>