<title>SCOOP THERAPY</title>
<meta name="description" content="SCOOP THERAPY">
<meta name="keywords" content="SCOOP THERAPY">

<!-- Mobile Viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!-- Force IE to render best possible view -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- FAVICON -->
<link rel="icon" href="images/icons/favicon.png" type="image/png" sizes="16x16">

<!-- FONT -->
<link rel="stylesheet" type="text/css" href="//cloud.typography.com/6413692/7252952/css/fonts.css" />

<!-- CSS -->
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap.min.css" />
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap-theme.min.css" />
<link rel="stylesheet" href="css/font-awesome.min.css" />
<link rel="stylesheet" href="css/animate.min.css" />
<link rel="stylesheet" href="css/style.css" />
<link rel="stylesheet" href="css/mobile-style.css" />
<link rel="stylesheet" href="js/plugins/jquery.scrollbar.css" />

<!-- JS -->
<script type="text/javascript" src="js/vendors/jquery/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="js/vendors/jquery/jquery.mobile.custom.min.js"></script>
<script type="text/javascript" src="js/vendors/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery.mousewheel.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery.disablescroll.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TimelineMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenLite.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/plugins/ScrollToPlugin.min.js"></script>
<script type="text/javascript" src="js/plugins/instafeed.min.js"></script>
<script type="text/javascript" src="js/plugins/twitterFetcher.full.js"></script>
<script type="text/javascript" src="js/plugins/jquery.validate.min.js"></script>

<script type="text/javascript" src="js/plugins/jquery.scrollbar.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
<script type="text/javascript" src="js/main.js"></script>