<div id="menu-logo-wrapper" class="animated slideInDown">
	
	<div class="main-menu">		
		<div class="pull-left">
			<div class="toggle-menu-container">					
				<div class="toggle-menu">
					<a href="javascript:void(0)"> 
						<span class="nav-bar"></span> 
						<span class="nav-bar"></span> 
						<span class="nav-bar"></span> 
					</a> 
				</div>
			</div>
			<div class="main-nav-wrapper">
				<ul class="main-nav">
					<li><a href="index.html#about">About</a></li>
					<li><a href="index.html#flavours">Flavours</a></li>
					<li><a href="index.html#wholesale">Wholesale</a></li>
					<li><a href="index.html#news">News</a></li>
					<li><a href="index.html#locate">Locate</a></li>										
				</ul>				
			</div>
		</div>
		<a href="index.html" class="logo pull-right"><img src="images/logos/main-logo.png" alt=""></a>				
	</div>	

</div>